enum PickSource { generated, manual }

enum PlayStyle {
  balanced,
  hot,
  cold,
  random;

  String get label {
    switch (this) {
      case PlayStyle.balanced:
        return 'Balanced';
      case PlayStyle.hot:
        return 'Popular';
      case PlayStyle.cold:
        return 'Less frequent';
      case PlayStyle.random:
        return 'Random';
    }
  }

  /// Short emotional headline shown on the result card.
  String get tagline {
    switch (this) {
      case PlayStyle.balanced:
        return '⚖️ Balanced Pick';
      case PlayStyle.hot:
        return '🔥 Popular Pattern Pick';
      case PlayStyle.cold:
        return '❄️ Less Frequent Pick';
      case PlayStyle.random:
        return '🎲 Random Pick';
    }
  }

  /// One-liner shown under the tagline.
  String get taglineSubtitle {
    switch (this) {
      case PlayStyle.balanced:
        return 'Even spread across all number ranges.';
      case PlayStyle.hot:
        return 'These numbers appear more often in recent past results.';
      case PlayStyle.cold:
        return 'These numbers appear less often in recent past results.';
      case PlayStyle.random:
        return 'Completely random selection. Just for fun.';
    }
  }

  /// Stable lowercase_underscore value for analytics.
  /// Never change these once shipped — reports depend on them.
  String get analyticsName {
    switch (this) {
      case PlayStyle.balanced:
        return 'balanced';
      case PlayStyle.hot:
        return 'hot';
      case PlayStyle.cold:
        return 'cold';
      case PlayStyle.random:
        return 'random';
    }
  }

  String get description {
    switch (this) {
      case PlayStyle.balanced:
        return 'Even spread across the number range';
      case PlayStyle.hot:
        return 'Favors recently frequent numbers';
      case PlayStyle.cold:
        return 'Favors numbers less frequent in recent past results';
      case PlayStyle.random:
        return 'Pure random selection';
    }
  }
}

class GeneratedPick {
  final String id;
  final String lotteryId;
  final PlayStyle style;
  final List<int> mainNumbers;
  final List<int>? bonusNumbers;
  final DateTime createdAt;
  final String? pickLabel;     // e.g. "⭐ Best AI Pick" — set when saved from 3-picks
  final DateTime? drawDate;    // UTC date of the targeted draw
  final String? drawLabel;     // e.g. "Thu 17 Apr"
  final PickSource source;            // generated by AI or entered manually
  final bool hasNotifiedResultReady;  // true once result-ready notification fired

  GeneratedPick({
    String? id,
    required this.lotteryId,
    required this.style,
    required this.mainNumbers,
    this.bonusNumbers,
    required this.createdAt,
    this.pickLabel,
    this.drawDate,
    this.drawLabel,
    this.source = PickSource.generated,
    this.hasNotifiedResultReady = false,
  }) : id = id ?? '${createdAt.millisecondsSinceEpoch}_${lotteryId.hashCode.abs()}';

  String get countryCode {
    if (lotteryId.startsWith('us_')) return 'US';
    if (lotteryId.startsWith('au_')) return 'AU';
    return 'OTHER';
  }

  String get displayLabel => pickLabel ?? style.tagline;
}
