import '../l10n/generated/app_localizations_en.dart';

enum PickSource { generated, manual }

enum PlayStyle {
  balanced,
  hot,
  cold,
  random;

  static final _l10n = AppLocalizationsEn();

  String get label {
    switch (this) {
      case PlayStyle.balanced:
        return _l10n.styleBalanced;
      case PlayStyle.hot:
        return _l10n.styleObservedPattern;
      case PlayStyle.cold:
        return _l10n.styleLessCommon;
      case PlayStyle.random:
        return _l10n.styleRandom;
    }
  }

  /// Short emotional headline shown on the result card.
  String get tagline {
    switch (this) {
      case PlayStyle.balanced:
        return _l10n.styleBalancedTagline;
      case PlayStyle.hot:
        return _l10n.styleHotTagline;
      case PlayStyle.cold:
        return _l10n.styleColdTagline;
      case PlayStyle.random:
        return _l10n.styleRandomTagline;
    }
  }

  /// One-liner shown under the tagline.
  String get taglineSubtitle {
    switch (this) {
      case PlayStyle.balanced:
        return _l10n.styleBalancedSubtitle;
      case PlayStyle.hot:
        return _l10n.styleHotSubtitle;
      case PlayStyle.cold:
        return _l10n.styleColdSubtitle;
      case PlayStyle.random:
        return _l10n.styleRandomSubtitle;
    }
  }

  /// Stable lowercase_underscore value for analytics.
  /// Never change these once shipped — reports depend on them.
  String get analyticsName {
    switch (this) {
      case PlayStyle.balanced:
        return 'balanced';
      case PlayStyle.hot:
        return 'hot';
      case PlayStyle.cold:
        return 'cold';
      case PlayStyle.random:
        return 'random';
    }
  }

  String get description {
    switch (this) {
      case PlayStyle.balanced:
        return _l10n.styleBalancedDescription;
      case PlayStyle.hot:
        return _l10n.styleHotDescription;
      case PlayStyle.cold:
        return _l10n.styleColdDescription;
      case PlayStyle.random:
        return _l10n.styleRandomDescription;
    }
  }
}

class GeneratedPick {
  final String id;
  final String lotteryId;
  final PlayStyle style;
  final List<int> mainNumbers;
  final List<int>? bonusNumbers;
  final DateTime createdAt;
  final String?
  pickLabel; // e.g. "⭐ Best AI Pick" — set when saved from 3-picks
  final DateTime? drawDate; // UTC date of the targeted draw
  final String? drawLabel; // e.g. "Thu 17 Apr"
  final PickSource source; // generated by AI or entered manually
  final bool
  hasNotifiedResultReady; // true once result-ready notification fired

  GeneratedPick({
    String? id,
    required this.lotteryId,
    required this.style,
    required this.mainNumbers,
    this.bonusNumbers,
    required this.createdAt,
    this.pickLabel,
    this.drawDate,
    this.drawLabel,
    this.source = PickSource.generated,
    this.hasNotifiedResultReady = false,
  }) : id =
           id ??
           '${createdAt.millisecondsSinceEpoch}_${lotteryId.hashCode.abs()}';

  String get countryCode {
    if (lotteryId.startsWith('us_')) return 'US';
    if (lotteryId.startsWith('au_')) return 'AU';
    if (lotteryId.startsWith('uk_')) return 'GB';
    if (lotteryId.startsWith('ca_')) return 'CA';
    return 'OTHER';
  }

  String get displayLabel => pickLabel ?? style.tagline;
}
